// <auto-generated />
using System;
using AlitasGo.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlitasGo.Repository.Migrations
{
    [DbContext(typeof(AlitasGoDbContext))]
    [Migration("20260926184214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlitasGo.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Activo = true,
                            Descripcion = "Alitas de pollo en diferentes presentaciones",
                            Nombre = "Alitas"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Activo = true,
                            Descripcion = "Gaseosas, cervezas y jugos",
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Activo = true,
                            Descripcion = "Papas fritas, yucas y ensaladas",
                            Nombre = "Acompañamientos"
                        });
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.ComprobantePago", b =>
                {
                    b.Property<int>("ComprobanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComprobanteId"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MontoRecibido")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NumeroCorrelativo")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Vuelto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ComprobanteId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("ComprobantesPago");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.DetallePedido", b =>
                {
                    b.Property<int>("DetallePedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetallePedidoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NotasCocina")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("SaborSalsa")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DetallePedidoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Insumo", b =>
                {
                    b.Property<int>("InsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsumoId"));

                    b.Property<string>("CodigoInsumo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InsumoId");

                    b.HasIndex("CodigoInsumo")
                        .IsUnique();

                    b.ToTable("Insumos");

                    b.HasData(
                        new
                        {
                            InsumoId = 1,
                            CodigoInsumo = "INS-ALITA",
                            CostoUnitario = 1.5000m,
                            Nombre = "Alita de pollo",
                            StockActual = 200.00m,
                            StockMinimo = 30.00m,
                            UnidadMedida = "Unidades"
                        },
                        new
                        {
                            InsumoId = 2,
                            CodigoInsumo = "INS-SAL-BBQ",
                            CostoUnitario = 0.0200m,
                            Nombre = "Salsa BBQ",
                            StockActual = 5000.00m,
                            StockMinimo = 500.00m,
                            UnidadMedida = "Mililitros"
                        },
                        new
                        {
                            InsumoId = 3,
                            CodigoInsumo = "INS-SAL-BUF",
                            CostoUnitario = 0.0250m,
                            Nombre = "Salsa Buffalo",
                            StockActual = 4000.00m,
                            StockMinimo = 500.00m,
                            UnidadMedida = "Mililitros"
                        },
                        new
                        {
                            InsumoId = 4,
                            CodigoInsumo = "INS-SAL-ACE",
                            CostoUnitario = 0.0300m,
                            Nombre = "Salsa Acevichada",
                            StockActual = 3000.00m,
                            StockMinimo = 400.00m,
                            UnidadMedida = "Mililitros"
                        },
                        new
                        {
                            InsumoId = 5,
                            CodigoInsumo = "INS-PAPA",
                            CostoUnitario = 0.0030m,
                            Nombre = "Papa",
                            StockActual = 10000.00m,
                            StockMinimo = 2000.00m,
                            UnidadMedida = "Gramos"
                        });
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesaId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MesaId");

                    b.HasIndex("NumeroMesa")
                        .IsUnique();

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            MesaId = 1,
                            Capacidad = 4,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 1,
                            Ubicacion = "Salón Principal"
                        },
                        new
                        {
                            MesaId = 2,
                            Capacidad = 4,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 2,
                            Ubicacion = "Salón Principal"
                        },
                        new
                        {
                            MesaId = 3,
                            Capacidad = 4,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 3,
                            Ubicacion = "Salón Principal"
                        },
                        new
                        {
                            MesaId = 4,
                            Capacidad = 6,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 4,
                            Ubicacion = "Salón Principal"
                        },
                        new
                        {
                            MesaId = 5,
                            Capacidad = 6,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 5,
                            Ubicacion = "Salón Principal"
                        },
                        new
                        {
                            MesaId = 6,
                            Capacidad = 2,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 6,
                            Ubicacion = "Bar"
                        },
                        new
                        {
                            MesaId = 7,
                            Capacidad = 2,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 7,
                            Ubicacion = "Bar"
                        },
                        new
                        {
                            MesaId = 8,
                            Capacidad = 8,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 8,
                            Ubicacion = "Terraza"
                        },
                        new
                        {
                            MesaId = 9,
                            Capacidad = 8,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 9,
                            Ubicacion = "Terraza"
                        },
                        new
                        {
                            MesaId = 10,
                            Capacidad = 4,
                            Estado = "Disponible",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroMesa = 10,
                            Ubicacion = "Terraza"
                        });
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.MovimientoKardex", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockPosterior")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("StockPrevio")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MovimientoId");

                    b.HasIndex("InsumoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("MovimientosKardex");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<string>("CodigoPedido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalPagar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PedidoId");

                    b.HasIndex("CodigoPedido")
                        .IsUnique();

                    b.HasIndex("MesaId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RequiereSabor")
                        .HasColumnType("bit");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Codigo = "ALT-06",
                            Descripcion = "6 alitas a la parrilla con salsa a elegir",
                            Nombre = "Alitas x6",
                            PrecioUnitario = 22.00m,
                            RequiereSabor = true
                        },
                        new
                        {
                            ProductoId = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Codigo = "ALT-12",
                            Descripcion = "12 alitas a la parrilla con salsa a elegir",
                            Nombre = "Alitas x12",
                            PrecioUnitario = 39.00m,
                            RequiereSabor = true
                        },
                        new
                        {
                            ProductoId = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Codigo = "ALT-20",
                            Descripcion = "20 alitas a la parrilla con salsa a elegir",
                            Nombre = "Alitas x20",
                            PrecioUnitario = 60.00m,
                            RequiereSabor = true
                        },
                        new
                        {
                            ProductoId = 4,
                            Activo = true,
                            CategoriaId = 3,
                            Codigo = "PAP-FRI",
                            Descripcion = "Porción de papas fritas crujientes",
                            Nombre = "Papas Fritas",
                            PrecioUnitario = 10.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            ProductoId = 5,
                            Activo = true,
                            CategoriaId = 2,
                            Codigo = "BEB-GAS",
                            Descripcion = "Gaseosa personal 500ml",
                            Nombre = "Gaseosa 500ml",
                            PrecioUnitario = 5.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            ProductoId = 6,
                            Activo = true,
                            CategoriaId = 2,
                            Codigo = "BEB-CER",
                            Descripcion = "Cerveza rubia 620ml",
                            Nombre = "Cerveza 620ml",
                            PrecioUnitario = 9.00m,
                            RequiereSabor = false
                        });
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.RecetaProducto", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetaId"));

                    b.Property<decimal>("CantidadRequerida")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("RecetaId");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ProductoId", "InsumoId")
                        .IsUnique();

                    b.ToTable("RecetasProducto");

                    b.HasData(
                        new
                        {
                            RecetaId = 1,
                            CantidadRequerida = 6.0000m,
                            InsumoId = 1,
                            ProductoId = 1
                        },
                        new
                        {
                            RecetaId = 2,
                            CantidadRequerida = 60.0000m,
                            InsumoId = 2,
                            ProductoId = 1
                        },
                        new
                        {
                            RecetaId = 3,
                            CantidadRequerida = 12.0000m,
                            InsumoId = 1,
                            ProductoId = 2
                        },
                        new
                        {
                            RecetaId = 4,
                            CantidadRequerida = 80.0000m,
                            InsumoId = 2,
                            ProductoId = 2
                        },
                        new
                        {
                            RecetaId = 5,
                            CantidadRequerida = 20.0000m,
                            InsumoId = 1,
                            ProductoId = 3
                        },
                        new
                        {
                            RecetaId = 6,
                            CantidadRequerida = 120.0000m,
                            InsumoId = 2,
                            ProductoId = 3
                        },
                        new
                        {
                            RecetaId = 7,
                            CantidadRequerida = 200.0000m,
                            InsumoId = 5,
                            ProductoId = 4
                        });
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.ComprobantePago", b =>
                {
                    b.HasOne("AlitasGo.Domain.Entities.Pedido", "Pedido")
                        .WithOne("ComprobantePago")
                        .HasForeignKey("AlitasGo.Domain.Entities.ComprobantePago", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.DetallePedido", b =>
                {
                    b.HasOne("AlitasGo.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGo.Domain.Entities.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.MovimientoKardex", b =>
                {
                    b.HasOne("AlitasGo.Domain.Entities.Insumo", "Insumo")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlitasGo.Domain.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Insumo");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("AlitasGo.Domain.Entities.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Producto", b =>
                {
                    b.HasOne("AlitasGo.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.RecetaProducto", b =>
                {
                    b.HasOne("AlitasGo.Domain.Entities.Insumo", "Insumo")
                        .WithMany("Recetas")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlitasGo.Domain.Entities.Producto", "Producto")
                        .WithMany("Recetas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Insumo", b =>
                {
                    b.Navigation("MovimientosKardex");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("ComprobantePago");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AlitasGo.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("Recetas");
                });
#pragma warning restore 612, 618
        }
    }
}
